# Schema for the configuration files of the Chalk Token module.
chalk_token.settings:
  type: config_object
  label: 'Chalk Token settings'
  mapping:
    example:
      type: string
      label: 'Example'

chalk_token.plugin.foundation:
  type: config_object
  label: 'Foundation token configuration'
  mapping:
    token_value:
      type: string
      label: 'Token Value'
    token_description:
      type: string
      label: 'Token Description'

